elements = {
-- cpu1 monitor
{
kind = 'ring_graph',
center = {x=260, y=260},
radius = 150,
conky_value = 'cpu cpu1',
max_value = 100,
critical_threshold = 90,
bar_color = '0x16ffff',
bar_alpha = 1.0,
bar_thickness = 10,
background_color = '0xffffff',
background_alpha = 1.0,
background_thickness = 8,
change_color_on_critical = false,
change_alpha_on_critical = false,
change_thickness_on_critical = false,
background_color_critical = '0x000000',
background_alpha_critical = 1.0,
background_thickness_critical = 8,
bar_color_critical = '0x000000',
bar_alpha_critical = 1,
bar_thickness_critical = 8,
start_angle = 360,
end_angle = 240,
graduated = True,
number_graduation = 10,
angle_between_graduation = 10,
},
--  cpu2 monitor
{
kind = 'ring_graph',
center = {x=260, y=260},
radius = 140,
conky_value = 'cpu cpu2',
max_value = 100,
critical_threshold = 90,
bar_color = '0x16ffff',
bar_alpha = 1.0,
bar_thickness = 10,
background_color = '0xffffff',
background_alpha = 1.0,
background_thickness = 8,
change_color_on_critical = false,
change_alpha_on_critical = false,
change_thickness_on_critical = false,
background_color_critical = '0x000000',
background_alpha_critical = 1.0,
background_thickness_critical = 8,
bar_color_critical = '0x000000',
bar_alpha_critical = 1,
bar_thickness_critical = 8,
start_angle = 360,
end_angle = 240,
graduated = False,
number_graduation = 10,
angle_between_graduation = 10,
},
--  cpu3 monitor
{
kind = 'ring_graph',
center = {x=260, y=260},
radius = 130,
conky_value = 'cpu cpu3',
max_value = 100,
critical_threshold = 90,
bar_color = '0x16ffff',
bar_alpha = 1.0,
bar_thickness = 10,
background_color = '0xffffff',
background_alpha = 1.0,
background_thickness = 8,
change_color_on_critical = false,
change_alpha_on_critical = false,
change_thickness_on_critical = false,
background_color_critical = '0x000000',
background_alpha_critical = 1.0,
background_thickness_critical = 8,
bar_color_critical = '0x000000',
bar_alpha_critical = 1,
bar_thickness_critical = 8,
start_angle = 360,
end_angle = 240,
graduated = False,
number_graduation = 10,
angle_between_graduation = 10,
},
--  cpu4 monitor
{
kind = 'ring_graph',
center = {x=260, y=260},
radius = 120,
conky_value = 'cpu cpu4',
max_value = 100,
critical_threshold = 90,
bar_color = '0x16ffff',
bar_alpha = 1.0,
bar_thickness = 10,
background_color = '0xffffff',
background_alpha = 1.0,
background_thickness = 8,
change_color_on_critical = false,
change_alpha_on_critical = false,
change_thickness_on_critical = false,
background_color_critical = '0x000000',
background_alpha_critical = 1.0,
background_thickness_critical = 8,
bar_color_critical = '0x000000',
bar_alpha_critical = 1,
bar_thickness_critical = 8,
start_angle = 360,
end_angle = 240,
graduated = False,
number_graduation = 10,
angle_between_graduation = 10,
},
--  home monitor
{
kind = 'ring_graph',
center = {x=260, y=260},
radius = 145,
conky_value = 'fs_used_perc /home/',
max_value = 100,
critical_threshold = 90,
bar_color = '0x16ffff',
bar_alpha = 1.0,
bar_thickness = 20,
background_color = '0xffffff',
background_alpha = 1.0,
background_thickness = 8,
change_color_on_critical = false,
change_alpha_on_critical = false,
change_thickness_on_critical = false,
background_color_critical = '0x000000',
background_alpha_critical = 1.0,
background_thickness_critical = 8,
bar_color_critical = '0x000000',
bar_alpha_critical = 1,
bar_thickness_critical = 8,
start_angle = 120,
end_angle = 240,
graduated = True,
number_graduation = 10,
angle_between_graduation = 10,
},
--  root monitor
{
kind = 'ring_graph',
center = {x=260, y=260},
radius = 125,
conky_value = 'fs_used_perc /',
max_value = 100,
critical_threshold = 90,
bar_color = '0x16ffff',
bar_alpha = 1.0,
bar_thickness = 20,
background_color = '0xffffff',
background_alpha = 1.0,
background_thickness = 8,
change_color_on_critical = false,
change_alpha_on_critical = false,
change_thickness_on_critical = false,
background_color_critical = '0x000000',
background_alpha_critical = 1.0,
background_thickness_critical = 8,
bar_color_critical = '0x000000',
bar_alpha_critical = 1,
bar_thickness_critical = 8,
start_angle = 120,
end_angle = 240,
graduated = False,
number_graduation = 10,
angle_between_graduation = 10,
},
--  mem monitor
{
kind = 'ring_graph',
center = {x=260, y=260},
radius = 125,
conky_value = 'mem_perc',
max_value = 100,
critical_threshold = 90,
bar_color = '0x16ffff',
bar_alpha = 1.0,
bar_thickness = 20,
background_color = '0xffffff',
background_alpha = 1.0,
background_thickness = 8,
change_color_on_critical = false,
change_alpha_on_critical = false,
change_thickness_on_critical = false,
background_color_critical = '0x000000',
background_alpha_critical = 1.0,
background_thickness_critical = 8,
bar_color_critical = '0x000000',
bar_alpha_critical = 1,
bar_thickness_critical = 8,
start_angle = 0,
end_angle = 120,
graduated = False,
number_graduation = 10,
angle_between_graduation = 10,
},
--  swap monitor
{
kind = 'ring_graph',
center = {x=260, y=260},
radius = 145,
conky_value = 'swap_perc',
max_value = 100,
critical_threshold = 90,
bar_color = '0x16ffff',
bar_alpha = 1.0,
bar_thickness = 20,
background_color = '0xffffff',
background_alpha = 1.0,
background_thickness = 8,
change_color_on_critical = false,
change_alpha_on_critical = false,
change_thickness_on_critical = false,
background_color_critical = '0x000000',
background_alpha_critical = 1.0,
background_thickness_critical = 8,
bar_color_critical = '0x000000',
bar_alpha_critical = 1,
bar_thickness_critical = 8,
start_angle = 0,
end_angle = 120,
graduated = False,
number_graduation = 10,
angle_between_graduation = 10,
},
--  sep 2
{
kind = 'line',
from = {x=221, y=189},
to = {x=146, y=49},
color = '0xffffff',
alpha = 1.0,
thickness = 2,
graduated = False,
number_graduation = 10,
space_between_graduation = 1,
},
--  sep 1
{
kind = 'line',
from = {x=219, y=328},
to = {x=139, y=458},
color = '0xffffff',
alpha = 1.0,
thickness = 2,
graduated = False,
number_graduation = 10,
space_between_graduation = 1,
},
--  sep 3
{
kind = 'line',
from = {x=341, y=263},
to = {x=496, y=263},
color = '0xffffff',
alpha = 1.0,
thickness = 2,
graduated = False,
number_graduation = 10,
space_between_graduation = 1,
},
--  CPU text
{
kind = 'static_text',
from = {x=425, y=268},
text = 'CPU',
color = '0xffffff',
rotation_angle = 360,
font_size = 30,
font = 'Comic Sans MS',
bold = False,
italic = False,
alpha = 1.0,
},
--  MEM text
{
kind = 'static_text',
from = {x=168, y=478},
text = 'Mem',
color = '0xffffff',
rotation_angle = 300,
font_size = 30,
font = 'Comic Sans MS',
bold = False,
italic = False,
alpha = 1.0,
},
--  disk text
{
kind = 'static_text',
from = {x=122, y=64},
text = 'Disk',
color = '0xffffff',
rotation_angle = 60,
font_size = 30,
font = 'Comic Sans MS',
bold = False,
italic = False,
alpha = 1.0,
},
--  line disk 1
{
kind = 'line',
from = {x=150, y=300},
to = {x=160, y=290},
color = '0xffffff',
alpha = 1.0,
thickness = 1,
graduated = False,
number_graduation = 10,
space_between_graduation = 1,
},
--  line disk 2
{
kind = 'line',
from = {x=160, y=290},
to = {x=199, y=290},
color = '0xffffff',
alpha = 1.0,
thickness = 1,
graduated = False,
number_graduation = 10,
space_between_graduation = 1,
},
--  static_text
{
kind = 'static_text',
from = {x=169, y=290},
text = 'root',
color = '0xffffff',
rotation_angle = 360,
font_size = 12,
font = 'Comic Sans MS',
bold = False,
italic = False,
alpha = 1.0,
},
--  line
{
kind = 'line',
from = {x=106, y=252},
to = {x=96, y=267},
color = '0xffffff',
alpha = 1.0,
thickness = 1,
graduated = False,
number_graduation = 10,
space_between_graduation = 1,
},
--  line
{
kind = 'line',
from = {x=95, y=267},
to = {x=70, y=267},
color = '0xffffff',
alpha = 1.0,
thickness = 1,
graduated = False,
number_graduation = 10,
space_between_graduation = 1,
},
--  static_text
{
kind = 'static_text',
from = {x=69, y=267},
text = 'home',
color = '0xffffff',
rotation_angle = 360,
font_size = 12,
font = 'Comic Sans MS',
bold = False,
italic = False,
alpha = 1.0,
},
--  line
{
kind = 'line',
from = {x=303, y=366},
to = {x=288, y=356},
color = '0xffffff',
alpha = 1.0,
thickness = 1,
graduated = False,
number_graduation = 10,
space_between_graduation = 1,
},
--  line
{
kind = 'line',
from = {x=286, y=355},
to = {x=255, y=355},
color = '0xffffff',
alpha = 1.0,
thickness = 1,
graduated = False,
number_graduation = 10,
space_between_graduation = 1,
},
--  static_text
{
kind = 'static_text',
from = {x=259, y=355},
text = 'ram',
color = '0xffffff',
rotation_angle = 360,
font_size = 12,
font = 'Comic Sans MS',
bold = False,
italic = False,
alpha = 1.0,
},
--  line
{
kind = 'line',
from = {x=270, y=415},
to = {x=290, y=430},
color = '0xffffff',
alpha = 1.0,
thickness = 1,
graduated = False,
number_graduation = 10,
space_between_graduation = 1,
},
--  line
{
kind = 'line',
from = {x=291, y=430},
to = {x=321, y=430},
color = '0xffffff',
alpha = 1.0,
thickness = 1,
graduated = False,
number_graduation = 10,
space_between_graduation = 1,
},
--  static_text
{
kind = 'static_text',
from = {x=295, y=432},
text = 'swap',
color = '0xffffff',
rotation_angle = 360,
font_size = 12,
font = 'Comic Sans MS',
bold = False,
italic = False,
alpha = 1.0,
}
}