elements = {
-- smallone
{
kind = 'ellipse_graph',
center = {x=292, y=275},
radius = 98,
conky_value = 'cpu cpu0',
width = 98,
height = 98,
max_value = 100,
critical_threshold = 90,
background_color = '0xffffff',
background_alpha = 1,
background_thickness = 8,
bar_color = '0xffffff',
bar_alpha = 1,
bar_thickness = 8,
change_color_on_critical = false,
change_alpha_on_critical = false,
change_thickness_on_critical = false,
background_color_critical = '0xffffff',
background_alpha_critical = 1,
background_thickness_critical = 10,
bar_color_critical = '0xffffff',
bar_alpha_critical = 1,
bar_thickness_critical = 10,
start_angle = 0,
end_angle = 360,
graduated = False,
number_graduation = 10,
angle_between_graduation = 10,
}
}