elements = {
-- ellipse_#1
{
kind = 'ellipse',
center = {x=236, y=236},
radius = 156,
height = 156,
width = 156,
color = '0xffffff',
alpha = 1.0,
thickness = 8,
start_angle = 0,
end_angle = 360,
graduated = False,
number_graduation = 10,
angle_between_graduation = 10,
},
-- ring_graph_#2
{
kind = 'ring_graph',
center = {x=300, y=300},
radius = 131,
conky_value = 'fs_used_perc /home/',
max_value = 100,
critical_threshold = 90,
bar_color = '0x16ffff',
bar_alpha = 1,
bar_thickness = 8,
background_color = '0xffffff',
background_alpha = 1,
background_thickness = 8,
change_color_on_critical = false,
change_alpha_on_critical = false,
change_thickness_on_critical = false,
background_color_critical = '0x000000',
background_alpha_critical = 1,
background_thickness_critical = 8,
bar_color_critical = '0x000000',
bar_alpha_critical = 1,
bar_thickness_critical = 8,
start_angle = 0,
end_angle = 360,
graduated = False,
number_graduation = 10,
angle_between_graduation = 10,
},
-- ring_graph_#3
{
kind = 'ring_graph',
center = {x=300, y=300},
radius = 177,
conky_value = 'fs_used_perc /home/',
max_value = 100,
critical_threshold = 90,
bar_color = '0x16ffff',
bar_alpha = 1,
bar_thickness = 8,
background_color = '0xffffff',
background_alpha = 1,
background_thickness = 8,
change_color_on_critical = false,
change_alpha_on_critical = false,
change_thickness_on_critical = false,
background_color_critical = '0x000000',
background_alpha_critical = 1,
background_thickness_critical = 8,
bar_color_critical = '0x000000',
bar_alpha_critical = 1,
bar_thickness_critical = 8,
start_angle = 0,
end_angle = 360,
graduated = False,
number_graduation = 10,
angle_between_graduation = 10,
},
--  ring_graph_#2
{
kind = 'ring_graph',
center = {x=300, y=300},
radius = 131,
conky_value = 'fs_used_perc /home/',
max_value = 100,
critical_threshold = 90,
bar_color = '0x16ffff',
bar_alpha = 1.0,
bar_thickness = 8,
background_color = '0xffffff',
background_alpha = 1.0,
background_thickness = 8,
change_color_on_critical = false,
change_alpha_on_critical = false,
change_thickness_on_critical = false,
background_color_critical = '0x000000',
background_alpha_critical = 1.0,
background_thickness_critical = 8,
bar_color_critical = '0x000000',
bar_alpha_critical = 1,
bar_thickness_critical = 8,
start_angle = 0,
end_angle = 360,
graduated = False,
number_graduation = 10,
angle_between_graduation = 10,
},
--  ring_graph_#3
{
kind = 'ring_graph',
center = {x=300, y=300},
radius = 177,
conky_value = 'fs_used_perc /home/',
max_value = 100,
critical_threshold = 90,
bar_color = '0x16ffff',
bar_alpha = 1.0,
bar_thickness = 8,
background_color = '0xffffff',
background_alpha = 1.0,
background_thickness = 8,
change_color_on_critical = false,
change_alpha_on_critical = false,
change_thickness_on_critical = false,
background_color_critical = '0x000000',
background_alpha_critical = 1.0,
background_thickness_critical = 8,
bar_color_critical = '0x000000',
bar_alpha_critical = 1,
bar_thickness_critical = 8,
start_angle = 0,
end_angle = 360,
graduated = False,
number_graduation = 10,
angle_between_graduation = 10,
},
--   ring_graph_#2
{
kind = 'ring_graph',
center = {x=300, y=300},
radius = 131,
conky_value = 'fs_used_perc /home/',
max_value = 100,
critical_threshold = 90,
bar_color = '0x16ffff',
bar_alpha = 1.0,
bar_thickness = 8,
background_color = '0xffffff',
background_alpha = 1.0,
background_thickness = 8,
change_color_on_critical = false,
change_alpha_on_critical = false,
change_thickness_on_critical = false,
background_color_critical = '0x000000',
background_alpha_critical = 1.0,
background_thickness_critical = 8,
bar_color_critical = '0x000000',
bar_alpha_critical = 1,
bar_thickness_critical = 8,
start_angle = 0,
end_angle = 360,
graduated = False,
number_graduation = 10,
angle_between_graduation = 10,
},
--   ring_graph_#3
{
kind = 'ring_graph',
center = {x=300, y=300},
radius = 177,
conky_value = 'fs_used_perc /home/',
max_value = 100,
critical_threshold = 90,
bar_color = '0x16ffff',
bar_alpha = 1.0,
bar_thickness = 8,
background_color = '0xffffff',
background_alpha = 1.0,
background_thickness = 8,
change_color_on_critical = false,
change_alpha_on_critical = false,
change_thickness_on_critical = false,
background_color_critical = '0x000000',
background_alpha_critical = 1.0,
background_thickness_critical = 8,
bar_color_critical = '0x000000',
bar_alpha_critical = 1,
bar_thickness_critical = 8,
start_angle = 0,
end_angle = 360,
graduated = False,
number_graduation = 10,
angle_between_graduation = 10,
},
--    ring_graph_#2
{
kind = 'ring_graph',
center = {x=300, y=300},
radius = 131,
conky_value = 'fs_used_perc /home/',
max_value = 100,
critical_threshold = 90,
bar_color = '0x16ffff',
bar_alpha = 1.0,
bar_thickness = 8,
background_color = '0xffffff',
background_alpha = 1.0,
background_thickness = 8,
change_color_on_critical = false,
change_alpha_on_critical = false,
change_thickness_on_critical = false,
background_color_critical = '0x000000',
background_alpha_critical = 1.0,
background_thickness_critical = 8,
bar_color_critical = '0x000000',
bar_alpha_critical = 1,
bar_thickness_critical = 8,
start_angle = 0,
end_angle = 360,
graduated = False,
number_graduation = 10,
angle_between_graduation = 10,
},
--    ring_graph_#3
{
kind = 'ring_graph',
center = {x=300, y=300},
radius = 177,
conky_value = 'fs_used_perc /home/',
max_value = 100,
critical_threshold = 90,
bar_color = '0x16ffff',
bar_alpha = 1.0,
bar_thickness = 8,
background_color = '0xffffff',
background_alpha = 1.0,
background_thickness = 8,
change_color_on_critical = false,
change_alpha_on_critical = false,
change_thickness_on_critical = false,
background_color_critical = '0x000000',
background_alpha_critical = 1.0,
background_thickness_critical = 8,
bar_color_critical = '0x000000',
bar_alpha_critical = 1,
bar_thickness_critical = 8,
start_angle = 0,
end_angle = 360,
graduated = False,
number_graduation = 10,
angle_between_graduation = 10,
},
--     ring_graph_#2
{
kind = 'ring_graph',
center = {x=300, y=300},
radius = 131,
conky_value = 'fs_used_perc /home/',
max_value = 100,
critical_threshold = 90,
bar_color = '0x16ffff',
bar_alpha = 1.0,
bar_thickness = 8,
background_color = '0xffffff',
background_alpha = 1.0,
background_thickness = 8,
change_color_on_critical = false,
change_alpha_on_critical = false,
change_thickness_on_critical = false,
background_color_critical = '0x000000',
background_alpha_critical = 1.0,
background_thickness_critical = 8,
bar_color_critical = '0x000000',
bar_alpha_critical = 1,
bar_thickness_critical = 8,
start_angle = 0,
end_angle = 360,
graduated = False,
number_graduation = 10,
angle_between_graduation = 10,
},
--     ring_graph_#3
{
kind = 'ring_graph',
center = {x=300, y=300},
radius = 177,
conky_value = 'fs_used_perc /home/',
max_value = 100,
critical_threshold = 90,
bar_color = '0x16ffff',
bar_alpha = 1.0,
bar_thickness = 8,
background_color = '0xffffff',
background_alpha = 1.0,
background_thickness = 8,
change_color_on_critical = false,
change_alpha_on_critical = false,
change_thickness_on_critical = false,
background_color_critical = '0x000000',
background_alpha_critical = 1.0,
background_thickness_critical = 8,
bar_color_critical = '0x000000',
bar_alpha_critical = 1,
bar_thickness_critical = 8,
start_angle = 0,
end_angle = 360,
graduated = False,
number_graduation = 10,
angle_between_graduation = 10,
},
--      ring_graph_#2
{
kind = 'ring_graph',
center = {x=300, y=300},
radius = 131,
conky_value = 'fs_used_perc /home/',
max_value = 100,
critical_threshold = 90,
bar_color = '0x16ffff',
bar_alpha = 1.0,
bar_thickness = 8,
background_color = '0xffffff',
background_alpha = 1.0,
background_thickness = 8,
change_color_on_critical = false,
change_alpha_on_critical = false,
change_thickness_on_critical = false,
background_color_critical = '0x000000',
background_alpha_critical = 1.0,
background_thickness_critical = 8,
bar_color_critical = '0x000000',
bar_alpha_critical = 1,
bar_thickness_critical = 8,
start_angle = 0,
end_angle = 360,
graduated = False,
number_graduation = 10,
angle_between_graduation = 10,
},
--      ring_graph_#3
{
kind = 'ring_graph',
center = {x=300, y=300},
radius = 177,
conky_value = 'fs_used_perc /home/',
max_value = 100,
critical_threshold = 90,
bar_color = '0x16ffff',
bar_alpha = 1.0,
bar_thickness = 8,
background_color = '0xffffff',
background_alpha = 1.0,
background_thickness = 8,
change_color_on_critical = false,
change_alpha_on_critical = false,
change_thickness_on_critical = false,
background_color_critical = '0x000000',
background_alpha_critical = 1.0,
background_thickness_critical = 8,
bar_color_critical = '0x000000',
bar_alpha_critical = 1,
bar_thickness_critical = 8,
start_angle = 0,
end_angle = 360,
graduated = False,
number_graduation = 10,
angle_between_graduation = 10,
},
--       ring_graph_#2
{
kind = 'ring_graph',
center = {x=300, y=300},
radius = 131,
conky_value = 'fs_used_perc /home/',
max_value = 100,
critical_threshold = 90,
bar_color = '0x16ffff',
bar_alpha = 1.0,
bar_thickness = 8,
background_color = '0xffffff',
background_alpha = 1.0,
background_thickness = 8,
change_color_on_critical = false,
change_alpha_on_critical = false,
change_thickness_on_critical = false,
background_color_critical = '0x000000',
background_alpha_critical = 1.0,
background_thickness_critical = 8,
bar_color_critical = '0x000000',
bar_alpha_critical = 1,
bar_thickness_critical = 8,
start_angle = 0,
end_angle = 360,
graduated = False,
number_graduation = 10,
angle_between_graduation = 10,
},
--       ring_graph_#3
{
kind = 'ring_graph',
center = {x=300, y=300},
radius = 177,
conky_value = 'fs_used_perc /home/',
max_value = 100,
critical_threshold = 90,
bar_color = '0x16ffff',
bar_alpha = 1.0,
bar_thickness = 8,
background_color = '0xffffff',
background_alpha = 1.0,
background_thickness = 8,
change_color_on_critical = false,
change_alpha_on_critical = false,
change_thickness_on_critical = false,
background_color_critical = '0x000000',
background_alpha_critical = 1.0,
background_thickness_critical = 8,
bar_color_critical = '0x000000',
bar_alpha_critical = 1,
bar_thickness_critical = 8,
start_angle = 0,
end_angle = 360,
graduated = False,
number_graduation = 10,
angle_between_graduation = 10,
},
--        ring_graph_#2
{
kind = 'ring_graph',
center = {x=300, y=300},
radius = 131,
conky_value = 'fs_used_perc /home/',
max_value = 100,
critical_threshold = 90,
bar_color = '0x16ffff',
bar_alpha = 1.0,
bar_thickness = 8,
background_color = '0xffffff',
background_alpha = 1.0,
background_thickness = 8,
change_color_on_critical = false,
change_alpha_on_critical = false,
change_thickness_on_critical = false,
background_color_critical = '0x000000',
background_alpha_critical = 1.0,
background_thickness_critical = 8,
bar_color_critical = '0x000000',
bar_alpha_critical = 1,
bar_thickness_critical = 8,
start_angle = 0,
end_angle = 360,
graduated = False,
number_graduation = 10,
angle_between_graduation = 10,
},
--        ring_graph_#3
{
kind = 'ring_graph',
center = {x=300, y=300},
radius = 177,
conky_value = 'fs_used_perc /home/',
max_value = 100,
critical_threshold = 90,
bar_color = '0x16ffff',
bar_alpha = 1.0,
bar_thickness = 8,
background_color = '0xffffff',
background_alpha = 1.0,
background_thickness = 8,
change_color_on_critical = false,
change_alpha_on_critical = false,
change_thickness_on_critical = false,
background_color_critical = '0x000000',
background_alpha_critical = 1.0,
background_thickness_critical = 8,
bar_color_critical = '0x000000',
bar_alpha_critical = 1,
bar_thickness_critical = 8,
start_angle = 0,
end_angle = 360,
graduated = False,
number_graduation = 10,
angle_between_graduation = 10,
},
--         ring_graph_#2
{
kind = 'ring_graph',
center = {x=300, y=300},
radius = 131,
conky_value = 'fs_used_perc /home/',
max_value = 100,
critical_threshold = 90,
bar_color = '0x16ffff',
bar_alpha = 1.0,
bar_thickness = 8,
background_color = '0xffffff',
background_alpha = 1.0,
background_thickness = 8,
change_color_on_critical = false,
change_alpha_on_critical = false,
change_thickness_on_critical = false,
background_color_critical = '0x000000',
background_alpha_critical = 1.0,
background_thickness_critical = 8,
bar_color_critical = '0x000000',
bar_alpha_critical = 1,
bar_thickness_critical = 8,
start_angle = 0,
end_angle = 360,
graduated = False,
number_graduation = 10,
angle_between_graduation = 10,
},
--         ring_graph_#3
{
kind = 'ring_graph',
center = {x=300, y=300},
radius = 177,
conky_value = 'fs_used_perc /home/',
max_value = 100,
critical_threshold = 90,
bar_color = '0x16ffff',
bar_alpha = 1.0,
bar_thickness = 8,
background_color = '0xffffff',
background_alpha = 1.0,
background_thickness = 8,
change_color_on_critical = false,
change_alpha_on_critical = false,
change_thickness_on_critical = false,
background_color_critical = '0x000000',
background_alpha_critical = 1.0,
background_thickness_critical = 8,
bar_color_critical = '0x000000',
bar_alpha_critical = 1,
bar_thickness_critical = 8,
start_angle = 0,
end_angle = 360,
graduated = False,
number_graduation = 10,
angle_between_graduation = 10,
},
--          ring_graph_#2
{
kind = 'ring_graph',
center = {x=300, y=300},
radius = 131,
conky_value = 'fs_used_perc /home/',
max_value = 100,
critical_threshold = 90,
bar_color = '0x16ffff',
bar_alpha = 1.0,
bar_thickness = 8,
background_color = '0xffffff',
background_alpha = 1.0,
background_thickness = 8,
change_color_on_critical = false,
change_alpha_on_critical = false,
change_thickness_on_critical = false,
background_color_critical = '0x000000',
background_alpha_critical = 1.0,
background_thickness_critical = 8,
bar_color_critical = '0x000000',
bar_alpha_critical = 1,
bar_thickness_critical = 8,
start_angle = 0,
end_angle = 360,
graduated = False,
number_graduation = 10,
angle_between_graduation = 10,
},
--          ring_graph_#3
{
kind = 'ring_graph',
center = {x=300, y=300},
radius = 177,
conky_value = 'fs_used_perc /home/',
max_value = 100,
critical_threshold = 90,
bar_color = '0x16ffff',
bar_alpha = 1.0,
bar_thickness = 8,
background_color = '0xffffff',
background_alpha = 1.0,
background_thickness = 8,
change_color_on_critical = false,
change_alpha_on_critical = false,
change_thickness_on_critical = false,
background_color_critical = '0x000000',
background_alpha_critical = 1.0,
background_thickness_critical = 8,
bar_color_critical = '0x000000',
bar_alpha_critical = 1,
bar_thickness_critical = 8,
start_angle = 0,
end_angle = 360,
graduated = False,
number_graduation = 10,
angle_between_graduation = 10,
},
--           ring_graph_#2
{
kind = 'ring_graph',
center = {x=300, y=300},
radius = 131,
conky_value = 'fs_used_perc /home/',
max_value = 100,
critical_threshold = 90,
bar_color = '0x16ffff',
bar_alpha = 1.0,
bar_thickness = 8,
background_color = '0xffffff',
background_alpha = 1.0,
background_thickness = 8,
change_color_on_critical = false,
change_alpha_on_critical = false,
change_thickness_on_critical = false,
background_color_critical = '0x000000',
background_alpha_critical = 1.0,
background_thickness_critical = 8,
bar_color_critical = '0x000000',
bar_alpha_critical = 1,
bar_thickness_critical = 8,
start_angle = 0,
end_angle = 360,
graduated = False,
number_graduation = 10,
angle_between_graduation = 10,
},
--           ring_graph_#3
{
kind = 'ring_graph',
center = {x=300, y=300},
radius = 177,
conky_value = 'fs_used_perc /home/',
max_value = 100,
critical_threshold = 90,
bar_color = '0x16ffff',
bar_alpha = 1.0,
bar_thickness = 8,
background_color = '0xffffff',
background_alpha = 1.0,
background_thickness = 8,
change_color_on_critical = false,
change_alpha_on_critical = false,
change_thickness_on_critical = false,
background_color_critical = '0x000000',
background_alpha_critical = 1.0,
background_thickness_critical = 8,
bar_color_critical = '0x000000',
bar_alpha_critical = 1,
bar_thickness_critical = 8,
start_angle = 0,
end_angle = 360,
graduated = False,
number_graduation = 10,
angle_between_graduation = 10,
}
}